"""initial

Revision ID: 0036c26d7c8f
Revises: 
Create Date: 2025-09-27 12:36:30.906466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.prompts import *
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '0036c26d7c8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    prompts = op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('seconds_left', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(prompts, [
    {
        "name": "summary",
        "text": summary_prompt,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "name": "short_summary",
        "text": short_summary_prompt,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "name": "protocol",
        "text": protocol_prompt,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    op.drop_table('transcriptions')
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('prompts')
    # ### end Alembic commands ###
