"""new summary prompt

Revision ID: 0eb2ff07263f
Revises: 0036c26d7c8f
Create Date: 2025-10-09 18:24:05.401618

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import Table, MetaData
from src.prompts import *
from src.db.models import Prompt


# revision identifiers, used by Alembic.
revision: str = "0eb2ff07263f"
down_revision: Union[str, Sequence[str], None] = "0036c26d7c8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    metadata = MetaData()
    table = Table("prompts", metadata, autoload_with=conn)
    conn.execute(
        table.update().where(table.c.name == "summary").values(text=summary_prompt)
    )
    conn.execute(
        table.update()
        .where(table.c.name == "short_summary")
        .values(text=short_summary_prompt)
    )
    conn.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
